version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_adservice:
    docker:
      - image: docker:17.05.0-ce-git

        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker            
      - run:
          name: build and push adservice image
          command: |
            cd src/adservice
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            # docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            docker push $image

  build_cartservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      source=cartservice  
      - run:
          name: build and push $source image
          command: |
            cd src/$source/src/
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_adservice
      - build_cartservice
      
