version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_adservice:
    docker:
      - image: ubuntu
        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: install docker
          command: |
            apt update
            apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            apt update
            apt install docker-ce
            usermod -aG docker ${USER}
      - run:
          name: build and push adservice image
          command: |
            cd src/adservice
            image=gitauwairimu/onlineshop:v.0.$CIRCLE_WORKFLOW_ID
            usermod -aG docker $USER
            docker build -t $image .
            docker push $image



# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_adservice
      #- test
