version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_adservice:
    docker:
      - image: alpine
        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: install docker
          command: |
            apk add --update docker openrc
            # service docker start
            # service docker status

      # - run:
      #     name: install docker
      #     command: |
      #       apt update
      #       apt install -y apt-transport-https ca-certificates curl software-properties-common
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      #       add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      #       apt update -y
      #       apt-get install -y docker-ce docker-ce-cli containerd.io
                
      - run:
          name: build and push adservice image
          command: |
            cd src/adservice
            image=gitauwairimu/onlineshop:v.0.$CIRCLE_WORKFLOW_ID
            sleep 120
            #chmod 666 /var/run/docker.sock
            rc-service docker enable
            rc-service docker restart
            docker build -t $image .
            docker push $image



# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_adservice
      #- test
