version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_adservice:
    docker:
      - image: amazon/aws-cli
        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: install docker
          command: |
            yum install -y yum-utils
            yum-config-manager \
              --add-repo \
              https://download.docker.com/linux/centos/docker-ce.repo
            yum install docker-ce docker-ce-cli
            systemctl start docker
      - run:
          name: build and push adservice image
          command: |
            cd src/adservice
            image=gitauwairimu/onlineshop:v.0.$CIRCLE_WORKFLOW_ID
            docker build -t $image
            docker push $image



# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_adservice
      #- test
