version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_adservice:
    docker:
      - image: centos
        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: install docker
          command: |
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

            yum check-update
            curl -fsSL https://get.docker.com/ | sh
            systemctl start docker
            systemctl status docker
            usermod -aG docker $(whoami)

      # - run:
      #     name: install docker
      #     command: |
      #       apt update
      #       apt install -y apt-transport-https ca-certificates curl software-properties-common
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      #       add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      #       apt update -y
      #       apt-get install -y docker-ce docker-ce-cli containerd.io
                
      - run:
          name: build and push adservice image
          command: |
            cd src/adservice
            image=gitauwairimu/onlineshop:v.0.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker push $image



# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_adservice
      #- test
