version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_adservice:
    docker:
      - image: docker:17.05.0-ce-git

        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker            
      - run:
          name: build and push adservice image
          command: |
            cd src/adservice
            image=gitauwairimu/onlineshop:adservice.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            # docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            docker push $image

  build_cartservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push cartservice image
          command: |
            source=cartservice
            cd src/$source/src/
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_checkoutservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push checkoutservice image
          command: |
            source=checkoutservice
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_emailservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push emailservice image
          command: |
            source=emailservice
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_frontend:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push frontend image
          command: |
            source=frontend
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_loadgenerator:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push loadgenerator image
          command: |
            source=loadgenerator
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_paymentservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push paymentservice image
          command: |
            source=paymentservice
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_productcatalogservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push productcatalogservice image
          command: |
            source=productcatalogservice
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_recommendationservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push recommendationservice image
          command: |
            source=recommendationservice
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_shippingservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push shippingservice image
          command: |
            source=shippingservice
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

  build_currencyservice:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: build and push currencyservice image
          command: |
            source=currencyservice
            cd src/$source
            image=gitauwairimu/onlineshop:$source.$CIRCLE_WORKFLOW_ID
            docker build -t $image .
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $image

# Orchestrate our job run sequence
workflows:
  build_and_push to dockerhub:
    jobs:
      - build_adservice
      - build_cartservice
      - build_checkoutservice
      - build_emailservice
      - build_frontend
      - build_loadgenerator
      - build_paymentservice
      - build_productcatalogservice
      - build_recommendationservice
      - build_shippingservice
      - build_currencyservice
