apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: emailservice
template:
  metadata:
    labels:
      app: emailservice
spec:
  containers: 
  - name: emailservice-container
    image: docker pull gitauwairimu/onlineshop:emailservice.d66b96cd-201a-49eb-a0f8-38f610a7e079
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
     

---
kind: Service 
apiVersion: v1 
metadata:
  name: emailservice-service 
spec:
  type: ClusterIP
  selector:
    app: emailservice

  ports:
    - Protocol: TCP
      port: 5000 
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
template:
  metadata:
    labels:
      app: recommendationservice
spec:
  containers: 
  - name: recommendationservice-container
    image: docker pull gitauwairimu/onlineshop:recommendationservice.d66b96cd-201a-49eb-a0f8-38f610a7e079
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalogservice-service:3550"
     

---
kind: Service 
apiVersion: v1 
metadata:
  name: recommendationservice-service
spec:
  type: ClusterIP
  selector:
    app: recommendationservice

  ports:
    - Protocol: TCP
      port: 8080 
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
template:
  metadata:
    labels:
      app: productcatalogservice
spec:
  containers: 
  - name: productcatalogservice-container
    image: docker pull gitauwairimu/onlineshop:productcatalogservice.d66b96cd-201a-49eb-a0f8-38f610a7e079
    ports:
    - containerPort: 3550
    env:
    - name: PORT
      value: "3550"  
 
---
kind: Service 
apiVersion: v1 
metadata:
  name: productcatalogservice-service
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice

  ports:
    - Protocol: TCP
      port: 3550 
      targetPort: 3550

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: paymentservice
template:
  metadata:
    labels:
      app: paymentservice
spec:
  containers: 
  - name: paymentservice-container
    image: docker pull gitauwairimu/onlineshop:paymentservice.d66b96cd-201a-49eb-a0f8-38f610a7e079
    ports:
    - containerPort: 50051
    env:
    - name: PORT
      value: "50051"  
 
---
kind: Service 
apiVersion: v1 
metadata:
  name: paymentservice-service 
spec:
  type: ClusterIP
  selector:
    app: paymentservice

  ports:
    - Protocol: TCP
      port: 50051
      targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: currencyservice
template:
  metadata:
    labels:
      app: currencyservice
spec:
  containers: 
  - name: currencyservice-container
    image: docker pull docker pull gitauwairimu/onlineshop:currencyservice.d01c5946-ffb9-4866-a0e5-927fa67f3017
    ports:
    - containerPort: 7000
    env:
    - name: PORT
      value: "7000"  
 
---
kind: Service 
apiVersion: v1 
metadata:
  name: currencyservice-service
spec:
  type: ClusterIP
  selector:
    app: currencyservice

  ports:
    - Protocol: TCP
      port: 7000
      targetPort: 7000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: shippingservice
template:
  metadata:
    labels:
      app: shippingservice
spec:
  containers: 
  - name: shippingservice-container
    image: docker pull docker pull gitauwairimu/onlineshop:shippingservice.d01c5946-ffb9-4866-a0e5-927fa67f3017
    ports:
    - containerPort: 50051
    env:
    - name: PORT
      value: "50051"  
 
---
kind: Service 
apiVersion: v1 
metadata:
  name: shippingservice-service
spec:
  type: ClusterIP
  selector:
    app: shippingservice

  ports:
    - Protocol: TCP
      port: 50051
      targetPort: 50051


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: adservice
template:
  metadata:
    labels:
      app: adservice
spec:
  containers: 
  - name: adservice-container
    image: docker pull docker pull gitauwairimu/onlineshop:adservice.d01c5946-ffb9-4866-a0e5-927fa67f3017
    ports:
    - containerPort: 9555
    env:
    - name: PORT
      value: "9555"  
---
kind: Service 
apiVersion: v1 
metadata:
  name: adservice-service
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - Protocol: TCP
      port: 9555
      targetPort: 9555

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: cartservice
template:
  metadata:
    labels:
      app: cartservice
spec:
  containers: 
  - name: cartservice-container
    image: docker pull docker pull gitauwairimu/onlineshop:cartservice.d01c5946-ffb9-4866-a0e5-927fa67f3017
    ports:
    - containerPort: 7070
    env:
    - name: PORT
      value: "7070"
    - name: REDIS_ADDR
      value: "redis-cart-service:6379"
---
kind: Service 
apiVersion: v1 
metadata:
  name: cartservice-service
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - Protocol: TCP
      port: 7070
      targetPort: 7070

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
replicas: 1
  selector:
    matchLabels:
      app: redis-cart
template:
  metadata:
    labels:
      app: redis-cart
spec:
  containers: 
  - name: redis-cart-container
    image: redis:alpine
    ports:
    - containerPort: 6379
    env:
    - name: PORT
      value: "6379"
    volumeMounts:
    - name: redis-data
      mountPath: /data
  volumes:
  - name: redis-data:
    emptyDir {}

---
kind: Service 
apiVersion: v1 
metadata:
  name: redis-cart-service
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
    - Protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
template:
  metadata:
    labels:
      app: checkoutservice
spec:
  containers: 
  - name: checkoutservice-container
    image: docker pull docker pull gitauwairimu/onlineshop:checkoutservice.d01c5946-ffb9-4866-a0e5-927fa67f3017
    ports:
    - containerPort: 5050
    env:
    - name: PORT
      value: "5050"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalogservice-service:3550"
    - name: CURRENCY_SERVICE_ADDR
      value: "currencyservice-service:7000"
    - name: CART_SERVICE_ADDR
      value: "cartservice-service:7070"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "recommendationservice-service:8080"
    - name: SHIPPING_SERVICE_ADDR
      value: "shippingservice-service:50051"
    - name: EMAIL_SERVICE_ADDR
      value: "emailservice-service:8080"
    - name: PAYMENT_SERVICE_ADDR
      value: "paymentservice-service:50051"

---
kind: Service 
apiVersion: v1 
metadata:
  name: checkoutservice-service:5050
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - Protocol: TCP
      port: 5050
      targetPort: 5050


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
replicas: 1
  selector:
    matchLabels:
      app: frontend
template:
  metadata:
    labels:
      app: frontend
spec:
  containers: 
  - name: frontend-container
    image: docker pull docker pull gitauwairimu/onlineshop:frontend.d01c5946-ffb9-4866-a0e5-927fa67f3017
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalogservice-service:3550"
    - name: CURRENCY_SERVICE_ADDR
      value: "currencyservice-service:7000"
    - name: CART_SERVICE_ADDR
      value: "cartservice-service:7070"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "recommendationservice-service:8080"
    - name: SHIPPING_SERVICE_ADDR
      value: "shippingservice-service:50051"
    - name: EMAIL_SERVICE_ADDR
      value: "emailservice-service:8080"
    - name: PAYMENT_SERVICE_ADDR
      value: "paymentservice-service:50051"
    - name: CHECKOUT_SERVICE_ADDR
      value: "checkoutservice-service:5050"
    - name: AD_SERVICE_ADDR
      value: "adservice-service:9555"
      
---
kind: Service 
apiVersion: v1 
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - Protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007